/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { OrderedProductsSpec } from '../models/orderedProductsSpec';
import { PostingDetailsErrors } from '../models/postingDetailsErrors';
import { RecruiterInfoErrors } from '../models/recruiterInfoErrors';

/**
 * Creates an instance of OrderinganewCampaignwithPortfolioV2taxonomyresponse1
 */
interface OrderinganewCampaignwithPortfolioV2taxonomyresponse1 {
  companyId: string[];
  postingDetails: PostingDetailsErrors;
  targetGroup: string[];
  recruiterInfo: RecruiterInfoErrors;
  orderedProducts: string[];
  orderedProductsSpecs: OrderedProductsSpec[];
}

export class OrderinganewCampaignwithPortfolioV2taxonomyresponse1Error extends ApiError<OrderinganewCampaignwithPortfolioV2taxonomyresponse1> {}
