/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of TakeaCampaignofflineresponse1
 */
interface TakeaCampaignofflineresponse1 {
  campaignId: string;
}

export class TakeaCampaignofflineresponse1Error extends ApiError<TakeaCampaignofflineresponse1> {}
