/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of TakeaCampaignofflineresponse2
 */
interface TakeaCampaignofflineresponse2 {
  campaignId: string[];
  status: string[];
}

export class TakeaCampaignofflineresponse2Error extends ApiError<TakeaCampaignofflineresponse2> {}
