/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  RequiredParametersEnum,
  requiredParametersEnumSchema,
} from './requiredParametersEnum';

export interface Autocomplete {
  requiredParameters?: RequiredParametersEnum;
}

export const autocompleteSchema: Schema<Autocomplete> = object({
  requiredParameters: [
    'required_parameters',
    optional(requiredParametersEnumSchema),
  ],
});
