/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface CampaignPosting {
  /** The name of the Product that was bought */
  name?: string;
  /** Number of clicks of the mentioned posting */
  clicks?: number;
}

export const campaignPostingSchema: Schema<CampaignPosting> = object({
  name: ['name', optional(string())],
  clicks: ['clicks', optional(number())],
});
