/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  OrderedProductsStatusItem,
  orderedProductsStatusItemSchema,
} from './orderedProductsStatusItem';
import { StatusEnum, statusEnumSchema } from './statusEnum';

export interface CampaignStatus {
  campaignId: string;
  /** Status of the campaign. One of the following */
  status?: StatusEnum;
  orderedProductsStatuses?: OrderedProductsStatusItem[];
}

export const campaignStatusSchema: Schema<CampaignStatus> = object({
  campaignId: ['campaignId', string()],
  status: ['status', optional(statusEnumSchema)],
  orderedProductsStatuses: [
    'orderedProductsStatuses',
    optional(array(lazy(() => orderedProductsStatusItemSchema))),
  ],
});
