/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  expandoObject,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface ChannelLiteModel {
  mcEnabled: boolean;
  id?: number;
  name?: string;
  url?: string;
  type?: string;
  [key: string]: unknown;
}

export const channelLiteModelSchema: Schema<ChannelLiteModel> = expandoObject({
  mcEnabled: ['mc_enabled', boolean()],
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  url: ['url', optional(string())],
  type: ['type', optional(string())],
});
