/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { CampaignStatus, campaignStatusSchema } from './campaignStatus';

export interface CheckCampaignStatusresponse {
  data?: CampaignStatus;
}

export const checkCampaignStatusresponseSchema: Schema<CheckCampaignStatusresponse> = object(
  { data: ['data', optional(lazy(() => campaignStatusSchema))] }
);
