/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ContractProduct {
  productId?: string;
  title?: string;
}

export const contractProductSchema: Schema<ContractProduct> = object({
  productId: ['product_id', optional(string())],
  title: ['title', optional(string())],
});
