/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ContractCredential {
  name: string;
  label: string;
  sort: string;
  description: string;
}

export const contractCredentialSchema: Schema<ContractCredential> = object({
  name: ['name', string()],
  label: ['label', string()],
  sort: ['sort', string()],
  description: ['description', string()],
});
