/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface ContractPurchasePrice {
  amount?: number;
  currency?: string;
}

export const contractPurchasePriceSchema: Schema<ContractPurchasePrice> = object(
  {
    amount: ['amount', optional(number())],
    currency: ['currency', optional(string())],
  }
);
