/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { ProductLite, productLiteSchema } from './productLite';
import { PurchasePrice, purchasePriceSchema } from './purchasePrice';

export interface Createanewcustomercontractresponse {
  customerId: string;
  contractId: string;
  channelId: number;
  credentials: string;
  className: string;
  facets?: unknown;
  product: ProductLite;
  postingRequirements: string;
  expiryDate?: string;
  credits?: number;
  purchasePrice?: PurchasePrice;
}

export const createanewcustomercontractresponseSchema: Schema<Createanewcustomercontractresponse> = object(
  {
    customerId: ['customer_id', string()],
    contractId: ['contract_id', string()],
    channelId: ['channel_id', number()],
    credentials: ['credentials', string()],
    className: ['class_name', string()],
    facets: ['facets', unknown()],
    product: ['product', lazy(() => productLiteSchema)],
    postingRequirements: ['posting_requirements', string()],
    expiryDate: ['expiry_date', optional(string())],
    credits: ['credits', optional(number())],
    purchasePrice: [
      'purchase_price',
      optional(lazy(() => purchasePriceSchema)),
    ],
  }
);
