/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { RangeEnum, rangeEnumSchema } from './rangeEnum';

export interface Duration {
  /** The range of the duration */
  range?: RangeEnum;
  /** The duration a vacancy is actively listed on a channel */
  period?: number;
}

export const durationSchema: Schema<Duration> = object({
  range: ['range', optional(rangeEnumSchema)],
  period: ['period', optional(number())],
});
