/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Name, nameSchema } from './name';

export interface EducationLevel {
  /** Internal Identification for an Education Level */
  id?: number;
  name?: Name[];
}

export const educationLevelSchema: Schema<EducationLevel> = object({
  id: ['id', optional(number())],
  name: ['name', optional(array(lazy(() => nameSchema)))],
});
