/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { RuleEnum, ruleEnumSchema } from './ruleEnum';

export interface FacetRule {
  rule: RuleEnum;
  data: string;
}

export const facetRuleSchema: Schema<FacetRule> = object({
  rule: ['rule', ruleEnumSchema],
  data: ['data', string()],
});
