/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

export interface FacetAutocomplete {
  term?: string;
  /** An object with `contract_credentials` data */
  credentials?: unknown;
}

export const facetAutocompleteSchema: Schema<FacetAutocomplete> = object({
  term: ['term', optional(string())],
  credentials: ['credentials', optional(unknown())],
});
