/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Industry(id, name) */
export interface Industry {
  id?: number;
  name: string;
}

export const industrySchema: Schema<Industry> = object({
  id: ['id', optional(number())],
  name: ['name', string()],
});
