/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** JobFunction(id, name, parent) */
export interface JobFunction {
  id?: number;
  name: string;
  parent?: number;
}

export const jobFunctionSchema: Schema<JobFunction> = object({
  id: ['id', optional(number())],
  name: ['name', string()],
  parent: ['parent', optional(number())],
});
