/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';

export interface JobFunctionTree {
  id: number;
  name: string;
  children: JobFunctionTree[];
}

export const jobFunctionTreeSchema: Schema<JobFunctionTree> = object({
  id: ['id', number()],
  name: ['name', string()],
  children: ['children', array(lazy(() => jobFunctionTreeSchema))],
});
