/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

/** JobTitle(id, name, job_function, industry, frequency, canonical, alias_of, active) */
export interface JobTitle {
  id: number;
  name: string;
}

export const jobTitleSchema: Schema<JobTitle> = object({
  id: ['id', number()],
  name: ['name', string()],
});
