/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';
import { ChannelLite, channelLiteSchema } from './channelLite';

export interface ListChannelsResponse {
  count: number;
  next: string;
  previous: string;
  results: ChannelLite[];
}

export const listChannelsResponseSchema: Schema<ListChannelsResponse> = object({
  count: ['count', number()],
  next: ['next', string()],
  previous: ['previous', string()],
  results: ['results', array(lazy(() => channelLiteSchema))],
});
