/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';
import {
  ChannelWithProducts,
  channelWithProductsSchema,
} from './channelWithProducts';

export interface ListchannelswithsupportforcontractsResponse {
  count: number;
  next: string;
  previous: string;
  results: ChannelWithProducts[];
}

export const listchannelswithsupportforcontractsResponseSchema: Schema<ListchannelswithsupportforcontractsResponse> = object(
  {
    count: ['count', number()],
    next: ['next', string()],
    previous: ['previous', string()],
    results: ['results', array(lazy(() => channelWithProductsSchema))],
  }
);
