/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Campaign, campaignSchema } from './campaign';

export interface ListasingleCampaignbythisPartnerresponse {
  data?: Campaign;
}

export const listasingleCampaignbythisPartnerresponseSchema: Schema<ListasingleCampaignbythisPartnerresponse> = object(
  { data: ['data', optional(lazy(() => campaignSchema))] }
);
