/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Campaign, campaignSchema } from './campaign';

export interface ListCampaignResponse {
  data?: Campaign;
}

export const listCampaignResponseSchema: Schema<ListCampaignResponse> = object({
  data: ['data', optional(lazy(() => campaignSchema))],
});
