/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Contract, contractSchema } from './contract';

export interface ListContractsResponse {
  /** count of elements in results */
  count?: number;
  /** link to get previous results */
  previous?: string;
  /** link to get next results */
  next?: string;
  results?: Contract[];
}

export const listContractsResponseSchema: Schema<ListContractsResponse> = object(
  {
    count: ['count', optional(number())],
    previous: ['previous', optional(string())],
    next: ['next', optional(string())],
    results: ['results', optional(array(lazy(() => contractSchema)))],
  }
);
