/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Name {
  /** ICU Locale code for the Language of the Education Level's name */
  languageCode?: string;
  /** Education Level name in one defined Language */
  value?: string;
}

export const nameSchema: Schema<Name> = object({
  languageCode: ['languageCode', optional(string())],
  value: ['value', optional(string())],
});
