/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Name3 {
  /** ICU Locale code for the Language of the Seniority's name */
  languageCode?: string;
  /** Seniority name in one defined Language */
  value?: string;
}

export const name3Schema: Schema<Name3> = object({
  languageCode: ['languageCode', optional(string())],
  value: ['value', optional(string())],
});
