/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface OrderinganewCampaignwithPortfolioV2taxonomyresponse {
  campaignId: string;
}

export const orderinganewCampaignwithPortfolioV2taxonomyresponseSchema: Schema<OrderinganewCampaignwithPortfolioV2taxonomyresponse> = object(
  { campaignId: ['campaignId', string()] }
);
