/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface OrderCampaignSuccessResponse {
  campaignId: string;
}

export const orderCampaignSuccessResponseSchema: Schema<OrderCampaignSuccessResponse> = object(
  { campaignId: ['campaignId', string()] }
);
