/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Status1Enum, status1EnumSchema } from './status1Enum';

export interface OrderedProductsStatusItem {
  productId?: string;
  /** Status of the product. One of the following */
  status?: Status1Enum;
  /** Additional information about product status */
  statusDescription?: string;
}

export const orderedProductsStatusItemSchema: Schema<OrderedProductsStatusItem> = object(
  {
    productId: ['productId', optional(string())],
    status: ['status', optional(status1EnumSchema)],
    statusDescription: ['statusDescription', optional(string())],
  }
);
