/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface OrderedProductsSpec {
  productId: string[];
  utm: string[];
}

export const orderedProductsSpecSchema: Schema<OrderedProductsSpec> = object({
  productId: ['productId', array(string())],
  utm: ['utm', array(string())],
});
