/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  PostingRequirements,
  postingRequirementsSchema,
} from './postingRequirements';

export interface OrderedProductsPostElement {
  /** Product Identification */
  productId?: string;
  /**
   * Query string for UTM parameters
   * **Pattern:** `/^([%.-_!*a-zA-Z0-9]{1,}=[%.-_!*+,;$()a-zA-Z0-9]{1,}[&]{0,}){1,}$/`
   */
  utm?: string;
  /** Contract Identifier needed for My Contracts product */
  contractId?: string;
  postingRequirements?: PostingRequirements;
}

export const orderedProductsPostElementSchema: Schema<OrderedProductsPostElement> = object(
  {
    productId: ['productId', optional(string())],
    utm: ['utm', optional(string())],
    contractId: ['contractId', optional(string())],
    postingRequirements: [
      'postingRequirements',
      optional(lazy(() => postingRequirementsSchema)),
    ],
  }
);
