/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  ChannelStatusEnum,
  channelStatusEnumSchema,
} from './channelStatusEnum';

export interface OrderedProductsStatusItem {
  productId?: string;
  /** Status of the product. One of the following */
  status?: ChannelStatusEnum;
  /** Additional information about product status */
  statusDescription?: string;
}

export const orderedProductsStatusItemSchema: Schema<OrderedProductsStatusItem> = object(
  {
    productId: ['productId', optional(string())],
    status: ['status', optional(channelStatusEnumSchema)],
    statusDescription: ['statusDescription', optional(string())],
  }
);
