/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface Organization {
  name: string[];
  companyLogo: string[];
}

export const organizationSchema: Schema<Organization> = object({
  name: ['name', array(string())],
  companyLogo: ['companyLogo', array(string())],
});
