/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface PostingWeeklyWorkingHours {
  from?: number;
  /** This value needs to be an positive integer */
  to: number;
}

export const postingWeeklyWorkingHoursSchema: Schema<PostingWeeklyWorkingHours> = object(
  { from: ['from', optional(number())], to: ['to', number()] }
);
