/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PostingOrganization {
  /** Name of the Company */
  name: string;
  /**
   * The company Logo that wants to be used on the posting. It has to be publicly available so it's picked up
   * and used for the different publishing platforms
   */
  companyLogo: string;
}

export const postingOrganizationSchema: Schema<PostingOrganization> = object({
  name: ['name', string()],
  companyLogo: ['companyLogo', string()],
});
