/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface PostingContactInfo {
  name: string;
  phoneNumber?: string;
  emailAddress?: string;
}

export const postingContactInfoSchema: Schema<PostingContactInfo> = object({
  name: ['name', string()],
  phoneNumber: ['phoneNumber', optional(string())],
  emailAddress: ['emailAddress', optional(string())],
});
