/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Organization, organizationSchema } from './organization';
import { SalaryIndication, salaryIndicationSchema } from './salaryIndication';
import {
  WeeklyWorkingHours,
  weeklyWorkingHoursSchema,
} from './weeklyWorkingHours';
import { WorkingLocation, workingLocationSchema } from './workingLocation';

export interface PostingDetailsErrors {
  title: string[];
  description: string[];
  yearsOfExperience: string[];
  employmentType: string[];
  organization: Organization;
  workingLocation: WorkingLocation;
  weeklyWorkingHours: WeeklyWorkingHours;
  salaryIndication: SalaryIndication;
  jobPageUrl: string[];
  applicationUrl: string[];
}

export const postingDetailsErrorsSchema: Schema<PostingDetailsErrors> = object({
  title: ['title', array(string())],
  description: ['description', array(string())],
  yearsOfExperience: ['yearsOfExperience', array(string())],
  employmentType: ['employmentType', array(string())],
  organization: ['organization', lazy(() => organizationSchema)],
  workingLocation: ['workingLocation', lazy(() => workingLocationSchema)],
  weeklyWorkingHours: [
    'weeklyWorkingHours',
    lazy(() => weeklyWorkingHoursSchema),
  ],
  salaryIndication: ['salaryIndication', lazy(() => salaryIndicationSchema)],
  jobPageUrl: ['jobPageUrl', array(string())],
  applicationUrl: ['applicationUrl', array(string())],
});
