/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { CurrencyEnum, currencyEnumSchema } from './currencyEnum';

export interface Price {
  /** Price amount in specified currency and 2 decimal places */
  amount?: number;
  /** ISO 4217 code for the Currency. */
  currency?: CurrencyEnum;
}

export const priceSchema: Schema<Price> = object({
  amount: ['amount', optional(number())],
  currency: ['currency', optional(currencyEnumSchema)],
});
