/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface ProductsDeliveryTime {
  daysToProcess?: number;
  daysToSetup?: number;
  totalDays?: number;
}

export const productsDeliveryTimeSchema: Schema<ProductsDeliveryTime> = object({
  daysToProcess: ['days_to_process', optional(number())],
  daysToSetup: ['days_to_setup', optional(number())],
  totalDays: ['total_days', optional(number())],
});
