/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ProductLite {
  productId: string;
  title: string;
}

export const productLiteSchema: Schema<ProductLite> = object({
  productId: ['product_id', string()],
  title: ['title', string()],
});
