/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface PurchasePrice {
  currency?: string;
  amount?: number;
}

export const purchasePriceSchema: Schema<PurchasePrice> = object({
  currency: ['currency', optional(string())],
  amount: ['amount', optional(number())],
});
