/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Range3 {
  /**
   * Minimum salary indication of the indicated period, if given, cannot be greater
   * than 'to', but equal to 'to' is allowed. This integer value should be specified in units (not cents).
   */
  from?: number;
  /** Maximum salary indication of the indicated period. This integer value should be specified in units (not cents). */
  to: number;
  /** The currency in which the range amount is expressed. Must be a valid ISO-4217 value. */
  currency?: string;
}

export const range3Schema: Schema<Range3> = object({
  from: ['from', optional(number())],
  to: ['to', number()],
  currency: ['currency', optional(string())],
});
