/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface Range4 {
  to: string[];
}

export const range4Schema: Schema<Range4> = object({
  to: ['to', array(string())],
});
