/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface RecruiterInfoErrors {
  name: string[];
}

export const recruiterInfoErrorsSchema: Schema<RecruiterInfoErrors> = object({
  name: ['name', array(string())],
});
