/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/**
 * Recruiter is the person using the ATS to create the Campaign and it's generally part of the Company whose Id
 * we request first.
 */
export interface RecruiterInfo {
  /** A vendor-related unique identification for the Recruiter */
  id?: string;
  name: string;
  emailAddress?: string;
}

export const recruiterInfoSchema: Schema<RecruiterInfo> = object({
  id: ['id', optional(string())],
  name: ['name', string()],
  emailAddress: ['emailAddress', optional(string())],
});
