/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Campaign, campaignSchema } from './campaign';

export interface ResultSet1 {
  /** Number of total results */
  total?: number;
  /** Results page size */
  limit?: number;
  /** Initial starting index for the results */
  offset?: number;
  /** A Page of Campaign Objects */
  data?: Campaign[];
}

export const resultSet1Schema: Schema<ResultSet1> = object({
  total: ['total', optional(number())],
  limit: ['limit', optional(number())],
  offset: ['offset', optional(number())],
  data: ['data', optional(array(lazy(() => campaignSchema)))],
});
