/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Range4, range4Schema } from './range4';

export interface SalaryIndication {
  period: string[];
  range: Range4;
}

export const salaryIndicationSchema: Schema<SalaryIndication> = object({
  period: ['period', array(string())],
  range: ['range', lazy(() => range4Schema)],
});
