/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Name3, name3Schema } from './name3';

export interface Seniority {
  /** Internal Identification for a Seniority Level */
  id?: number;
  name?: Name3[];
}

export const senioritySchema: Schema<Seniority> = object({
  id: ['id', optional(number())],
  name: ['name', optional(array(lazy(() => name3Schema)))],
});
