/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface TakeaCampaignofflinerequest {
  campaignId: string;
  status: string;
}

export const takeaCampaignofflinerequestSchema: Schema<TakeaCampaignofflinerequest> = object(
  { campaignId: ['campaignId', string()], status: ['status', string()] }
);
