/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TakeCampaignOfflineResponse {
  campaignId?: string;
}

export const takeCampaignOfflineResponseSchema: Schema<TakeCampaignOfflineResponse> = object(
  { campaignId: ['campaignId', optional(string())] }
);
