/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  TargetGroupElement,
  targetGroupElementSchema,
} from './targetGroupElement';

export interface TargetGroup {
  /** Education Level required by the Candidate. You can specify only one value. */
  educationLevel: TargetGroupElement[];
  /** Seniority Level expected by the Candidate. You can specify only one value. */
  seniority: TargetGroupElement[];
  /** The Industry related to the Position open. You can specify only one value. */
  industry: TargetGroupElement[];
  /** Job Category indicates the type of Position that's open. You can specify only one value. */
  jobCategory: TargetGroupElement[];
}

export const targetGroupSchema: Schema<TargetGroup> = object({
  educationLevel: [
    'educationLevel',
    array(lazy(() => targetGroupElementSchema)),
  ],
  seniority: ['seniority', array(lazy(() => targetGroupElementSchema))],
  industry: ['industry', array(lazy(() => targetGroupElementSchema))],
  jobCategory: ['jobCategory', array(lazy(() => targetGroupElementSchema))],
});
