/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface TargetGroupElement {
  /** The vonq name for this target group element */
  description: string;
  /** The Vonq ID representing this concept, as indicated in the [**`Taxonomy Endpoints`**](#reference/experimental-products-search) */
  vonqId: string;
}

export const targetGroupElementSchema: Schema<TargetGroupElement> = object({
  description: ['description', string()],
  vonqId: ['vonqId', string()],
});
