/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { Range1Enum, range1EnumSchema } from './range1Enum';

export interface TimeToProcess {
  /** The range of the time to process */
  range?: Range1Enum;
  /** The period of the time to process */
  period?: number;
}

export const timeToProcessSchema: Schema<TimeToProcess> = object({
  range: ['range', optional(range1EnumSchema)],
  period: ['period', optional(number())],
});
