/**
 * VONQ Hiring APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface WorkingLocation {
  addressLine1: string[];
  postcode: string[];
  city: string[];
  country: string[];
}

export const workingLocationSchema: Schema<WorkingLocation> = object({
  addressLine1: ['addressLine1', array(string())],
  postcode: ['postcode', array(string())],
  city: ['city', array(string())],
  country: ['country', array(string())],
});
